### ISSUE TITLE
Attempt to Store File Throws Error

### ISSUE THREAD

**Issue by dsschapira** [dsschapira/banner-timing-previewer#1]
When uploading a file, an error is thrown stating "Object of class StdClass could not be converted to a string in BannerObject.php on liine 31".

This is where we store the file sent from the front end to the BannerObject instance's file property.  This is almost definitely an issue of just getting the right data type but I'm still tracking down whether I need to manipulate it before sending the POST request from Angular or after it's received in the PHP backend.

**Comment by cngodles** [comment]
https://stackoverflow.com/questions/29547152/php-pdo-file-upload-and-save-to-mysql-database-results-in-obscure-file-breakage

**Comment by cngodles** [comment]
`PARAM_LOB`

**Comment by dsschapira** [comment]
Saving to server instead of database so this one doesn't apply anymore.
